### ISSUE TITLE
Export bitmap as jpg

### ISSUE THREAD

**Issue by sambody** [sepastian/inkscape-svg2jpg#1]
Hi. I have a suggestion for an additional feature: to be able to got to File > **Export bitmap**, and have JPG as a possible output format, not just png. 
I make web designs, and exporting _selections_ (not the whole document) is something I do all the time. In certain types of designs that rely heavily on images/photos, jpg export would be useful (smaller filesizes). Thanks.

**Comment by sepastian** [comment]
Hi, good point.

When adding functionality to export to JPEG, my first idea, too, was to extend the _File_ > _Export bitmap..._ dialog. However, the quickest and easiest solution proved to be extending the _Save As..._ dialog.

Maybe it is possible to add JPEG to _Export bitmap..._ as well, I will have another look at it when I have time.

**Comment by sepastian** [comment]
I obviously never found the time to look into this any further :fearful: I'm closing this for now.
